const keyFields = [
    "page_ok",
    "streak_bonus",
    "calculated_reward",
    "text_found",
    "frontpage_count",
    "uptime_streak",
    "images_found",
    "time_to_download",
    "actual_time_to_download",
    "time_up_percentage",
    "time_in_production_percentage",
    "time_since_last_fail",
    "total",
    "net_io_kb/s",
    "request_size",
    "reply_size_header",
    "errors",
    "connections",
    "request_rate_req/s",
    "reply_size_total",
    "reply_time_transfer",
    "test-duration",
    "reply",
    "cpu_time_system_seconds",
    "request_rate_ms/req",
    "replies/requests",
    "cpu_time_user_seconds",
    "cpu_time_user_percent",
    "cpu_time_system_percent",
]

export default keyFields